# TCL File Generated by Component Editor 18.1
# Mon Apr 29 22:44:26 CDT 2019
# DO NOT MODIFY


# 
# Synth_Controller "Synth_Controller" v1.0
#  2019.04.29.22:44:26
# Controls the Synthesizer
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Synth_Controller
# 
set_module_property DESCRIPTION "Controls the Synthesizer"
set_module_property NAME Synth_Controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "ECE-385 Custom IP"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Synth_Controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL control_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file control_interface.sv SYSTEM_VERILOG PATH control_interface.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL control_interface
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file control_interface.sv SYSTEM_VERILOG PATH control_interface.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point CLK
# 
add_interface CLK clock end
set_interface_property CLK clockRate 0
set_interface_property CLK ENABLED true
set_interface_property CLK EXPORT_OF ""
set_interface_property CLK PORT_NAME_MAP ""
set_interface_property CLK CMSIS_SVD_VARIABLES ""
set_interface_property CLK SVD_ADDRESS_GROUP ""

add_interface_port CLK CLK clk Input 1


# 
# connection point RESET
# 
add_interface RESET reset end
set_interface_property RESET associatedClock CLK
set_interface_property RESET synchronousEdges DEASSERT
set_interface_property RESET ENABLED true
set_interface_property RESET EXPORT_OF ""
set_interface_property RESET PORT_NAME_MAP ""
set_interface_property RESET CMSIS_SVD_VARIABLES ""
set_interface_property RESET SVD_ADDRESS_GROUP ""

add_interface_port RESET RESET reset Input 1


# 
# connection point ATTACK
# 
add_interface ATTACK conduit end
set_interface_property ATTACK associatedClock CLK
set_interface_property ATTACK associatedReset RESET
set_interface_property ATTACK ENABLED true
set_interface_property ATTACK EXPORT_OF ""
set_interface_property ATTACK PORT_NAME_MAP ""
set_interface_property ATTACK CMSIS_SVD_VARIABLES ""
set_interface_property ATTACK SVD_ADDRESS_GROUP ""

add_interface_port ATTACK ATTACK attack Output 16


# 
# connection point RLEASE
# 
add_interface RLEASE conduit end
set_interface_property RLEASE associatedClock CLK
set_interface_property RLEASE associatedReset RESET
set_interface_property RLEASE ENABLED true
set_interface_property RLEASE EXPORT_OF ""
set_interface_property RLEASE PORT_NAME_MAP ""
set_interface_property RLEASE CMSIS_SVD_VARIABLES ""
set_interface_property RLEASE SVD_ADDRESS_GROUP ""

add_interface_port RLEASE RLEASE rlease Output 16


# 
# connection point SUSTAIN
# 
add_interface SUSTAIN conduit end
set_interface_property SUSTAIN associatedClock CLK
set_interface_property SUSTAIN associatedReset RESET
set_interface_property SUSTAIN ENABLED true
set_interface_property SUSTAIN EXPORT_OF ""
set_interface_property SUSTAIN PORT_NAME_MAP ""
set_interface_property SUSTAIN CMSIS_SVD_VARIABLES ""
set_interface_property SUSTAIN SVD_ADDRESS_GROUP ""

add_interface_port SUSTAIN SUSTAIN sustain Output 16


# 
# connection point DECAY
# 
add_interface DECAY conduit end
set_interface_property DECAY associatedClock CLK
set_interface_property DECAY associatedReset RESET
set_interface_property DECAY ENABLED true
set_interface_property DECAY EXPORT_OF ""
set_interface_property DECAY PORT_NAME_MAP ""
set_interface_property DECAY CMSIS_SVD_VARIABLES ""
set_interface_property DECAY SVD_ADDRESS_GROUP ""

add_interface_port DECAY DECAY decay Output 16


# 
# connection point SHAPE1
# 
add_interface SHAPE1 conduit end
set_interface_property SHAPE1 associatedClock CLK
set_interface_property SHAPE1 associatedReset RESET
set_interface_property SHAPE1 ENABLED true
set_interface_property SHAPE1 EXPORT_OF ""
set_interface_property SHAPE1 PORT_NAME_MAP ""
set_interface_property SHAPE1 CMSIS_SVD_VARIABLES ""
set_interface_property SHAPE1 SVD_ADDRESS_GROUP ""

add_interface_port SHAPE1 SHAPE1 shape1 Output 2


# 
# connection point SHAPE0
# 
add_interface SHAPE0 conduit end
set_interface_property SHAPE0 associatedClock CLK
set_interface_property SHAPE0 associatedReset RESET
set_interface_property SHAPE0 ENABLED true
set_interface_property SHAPE0 EXPORT_OF ""
set_interface_property SHAPE0 PORT_NAME_MAP ""
set_interface_property SHAPE0 CMSIS_SVD_VARIABLES ""
set_interface_property SHAPE0 SVD_ADDRESS_GROUP ""

add_interface_port SHAPE0 SHAPE0 shape0 Output 2


# 
# connection point FREQ0
# 
add_interface FREQ0 conduit end
set_interface_property FREQ0 associatedClock CLK
set_interface_property FREQ0 associatedReset RESET
set_interface_property FREQ0 ENABLED true
set_interface_property FREQ0 EXPORT_OF ""
set_interface_property FREQ0 PORT_NAME_MAP ""
set_interface_property FREQ0 CMSIS_SVD_VARIABLES ""
set_interface_property FREQ0 SVD_ADDRESS_GROUP ""

add_interface_port FREQ0 FREQ0 freq0 Output 8


# 
# connection point KEY0
# 
add_interface KEY0 conduit end
set_interface_property KEY0 associatedClock CLK
set_interface_property KEY0 associatedReset RESET
set_interface_property KEY0 ENABLED true
set_interface_property KEY0 EXPORT_OF ""
set_interface_property KEY0 PORT_NAME_MAP ""
set_interface_property KEY0 CMSIS_SVD_VARIABLES ""
set_interface_property KEY0 SVD_ADDRESS_GROUP ""

add_interface_port KEY0 KEY0 key0 Output 1


# 
# connection point AMP1_0
# 
add_interface AMP1_0 conduit end
set_interface_property AMP1_0 associatedClock CLK
set_interface_property AMP1_0 associatedReset RESET
set_interface_property AMP1_0 ENABLED true
set_interface_property AMP1_0 EXPORT_OF ""
set_interface_property AMP1_0 PORT_NAME_MAP ""
set_interface_property AMP1_0 CMSIS_SVD_VARIABLES ""
set_interface_property AMP1_0 SVD_ADDRESS_GROUP ""

add_interface_port AMP1_0 AMP1_0 amp1_0 Output 16


# 
# connection point AMP0_0
# 
add_interface AMP0_0 conduit end
set_interface_property AMP0_0 associatedClock CLK
set_interface_property AMP0_0 associatedReset RESET
set_interface_property AMP0_0 ENABLED true
set_interface_property AMP0_0 EXPORT_OF ""
set_interface_property AMP0_0 PORT_NAME_MAP ""
set_interface_property AMP0_0 CMSIS_SVD_VARIABLES ""
set_interface_property AMP0_0 SVD_ADDRESS_GROUP ""

add_interface_port AMP0_0 AMP0_0 amp0_0 Output 16


# 
# connection point FREQ1
# 
add_interface FREQ1 conduit end
set_interface_property FREQ1 associatedClock CLK
set_interface_property FREQ1 associatedReset RESET
set_interface_property FREQ1 ENABLED true
set_interface_property FREQ1 EXPORT_OF ""
set_interface_property FREQ1 PORT_NAME_MAP ""
set_interface_property FREQ1 CMSIS_SVD_VARIABLES ""
set_interface_property FREQ1 SVD_ADDRESS_GROUP ""

add_interface_port FREQ1 FREQ1 freq1 Output 8


# 
# connection point KEY1
# 
add_interface KEY1 conduit end
set_interface_property KEY1 associatedClock CLK
set_interface_property KEY1 associatedReset RESET
set_interface_property KEY1 ENABLED true
set_interface_property KEY1 EXPORT_OF ""
set_interface_property KEY1 PORT_NAME_MAP ""
set_interface_property KEY1 CMSIS_SVD_VARIABLES ""
set_interface_property KEY1 SVD_ADDRESS_GROUP ""

add_interface_port KEY1 KEY1 key1 Output 1


# 
# connection point AMP1_1
# 
add_interface AMP1_1 conduit end
set_interface_property AMP1_1 associatedClock CLK
set_interface_property AMP1_1 associatedReset RESET
set_interface_property AMP1_1 ENABLED true
set_interface_property AMP1_1 EXPORT_OF ""
set_interface_property AMP1_1 PORT_NAME_MAP ""
set_interface_property AMP1_1 CMSIS_SVD_VARIABLES ""
set_interface_property AMP1_1 SVD_ADDRESS_GROUP ""

add_interface_port AMP1_1 AMP1_1 amp1_1 Output 16


# 
# connection point AMP0_1
# 
add_interface AMP0_1 conduit end
set_interface_property AMP0_1 associatedClock CLK
set_interface_property AMP0_1 associatedReset RESET
set_interface_property AMP0_1 ENABLED true
set_interface_property AMP0_1 EXPORT_OF ""
set_interface_property AMP0_1 PORT_NAME_MAP ""
set_interface_property AMP0_1 CMSIS_SVD_VARIABLES ""
set_interface_property AMP0_1 SVD_ADDRESS_GROUP ""

add_interface_port AMP0_1 AMP0_1 amp0_1 Output 16


# 
# connection point FREQ2
# 
add_interface FREQ2 conduit end
set_interface_property FREQ2 associatedClock CLK
set_interface_property FREQ2 associatedReset RESET
set_interface_property FREQ2 ENABLED true
set_interface_property FREQ2 EXPORT_OF ""
set_interface_property FREQ2 PORT_NAME_MAP ""
set_interface_property FREQ2 CMSIS_SVD_VARIABLES ""
set_interface_property FREQ2 SVD_ADDRESS_GROUP ""

add_interface_port FREQ2 FREQ2 freq2 Output 8


# 
# connection point KEY2
# 
add_interface KEY2 conduit end
set_interface_property KEY2 associatedClock CLK
set_interface_property KEY2 associatedReset RESET
set_interface_property KEY2 ENABLED true
set_interface_property KEY2 EXPORT_OF ""
set_interface_property KEY2 PORT_NAME_MAP ""
set_interface_property KEY2 CMSIS_SVD_VARIABLES ""
set_interface_property KEY2 SVD_ADDRESS_GROUP ""

add_interface_port KEY2 KEY2 key2 Output 1


# 
# connection point AMP1_2
# 
add_interface AMP1_2 conduit end
set_interface_property AMP1_2 associatedClock CLK
set_interface_property AMP1_2 associatedReset RESET
set_interface_property AMP1_2 ENABLED true
set_interface_property AMP1_2 EXPORT_OF ""
set_interface_property AMP1_2 PORT_NAME_MAP ""
set_interface_property AMP1_2 CMSIS_SVD_VARIABLES ""
set_interface_property AMP1_2 SVD_ADDRESS_GROUP ""

add_interface_port AMP1_2 AMP1_2 amp1_2 Output 16


# 
# connection point AMP0_2
# 
add_interface AMP0_2 conduit end
set_interface_property AMP0_2 associatedClock CLK
set_interface_property AMP0_2 associatedReset RESET
set_interface_property AMP0_2 ENABLED true
set_interface_property AMP0_2 EXPORT_OF ""
set_interface_property AMP0_2 PORT_NAME_MAP ""
set_interface_property AMP0_2 CMSIS_SVD_VARIABLES ""
set_interface_property AMP0_2 SVD_ADDRESS_GROUP ""

add_interface_port AMP0_2 AMP0_2 amp0_2 Output 16


# 
# connection point FREQ3
# 
add_interface FREQ3 conduit end
set_interface_property FREQ3 associatedClock CLK
set_interface_property FREQ3 associatedReset RESET
set_interface_property FREQ3 ENABLED true
set_interface_property FREQ3 EXPORT_OF ""
set_interface_property FREQ3 PORT_NAME_MAP ""
set_interface_property FREQ3 CMSIS_SVD_VARIABLES ""
set_interface_property FREQ3 SVD_ADDRESS_GROUP ""

add_interface_port FREQ3 FREQ3 freq3 Output 8


# 
# connection point KEY3
# 
add_interface KEY3 conduit end
set_interface_property KEY3 associatedClock CLK
set_interface_property KEY3 associatedReset RESET
set_interface_property KEY3 ENABLED true
set_interface_property KEY3 EXPORT_OF ""
set_interface_property KEY3 PORT_NAME_MAP ""
set_interface_property KEY3 CMSIS_SVD_VARIABLES ""
set_interface_property KEY3 SVD_ADDRESS_GROUP ""

add_interface_port KEY3 KEY3 key3 Output 1


# 
# connection point AMP1_3
# 
add_interface AMP1_3 conduit end
set_interface_property AMP1_3 associatedClock CLK
set_interface_property AMP1_3 associatedReset RESET
set_interface_property AMP1_3 ENABLED true
set_interface_property AMP1_3 EXPORT_OF ""
set_interface_property AMP1_3 PORT_NAME_MAP ""
set_interface_property AMP1_3 CMSIS_SVD_VARIABLES ""
set_interface_property AMP1_3 SVD_ADDRESS_GROUP ""

add_interface_port AMP1_3 AMP1_3 amp1_3 Output 16


# 
# connection point AMP0_3
# 
add_interface AMP0_3 conduit end
set_interface_property AMP0_3 associatedClock CLK
set_interface_property AMP0_3 associatedReset RESET
set_interface_property AMP0_3 ENABLED true
set_interface_property AMP0_3 EXPORT_OF ""
set_interface_property AMP0_3 PORT_NAME_MAP ""
set_interface_property AMP0_3 CMSIS_SVD_VARIABLES ""
set_interface_property AMP0_3 SVD_ADDRESS_GROUP ""

add_interface_port AMP0_3 AMP0_3 amp0_3 Output 16


# 
# connection point FREQ4
# 
add_interface FREQ4 conduit end
set_interface_property FREQ4 associatedClock CLK
set_interface_property FREQ4 associatedReset RESET
set_interface_property FREQ4 ENABLED true
set_interface_property FREQ4 EXPORT_OF ""
set_interface_property FREQ4 PORT_NAME_MAP ""
set_interface_property FREQ4 CMSIS_SVD_VARIABLES ""
set_interface_property FREQ4 SVD_ADDRESS_GROUP ""

add_interface_port FREQ4 FREQ4 freq4 Output 8


# 
# connection point KEY4
# 
add_interface KEY4 conduit end
set_interface_property KEY4 associatedClock CLK
set_interface_property KEY4 associatedReset RESET
set_interface_property KEY4 ENABLED true
set_interface_property KEY4 EXPORT_OF ""
set_interface_property KEY4 PORT_NAME_MAP ""
set_interface_property KEY4 CMSIS_SVD_VARIABLES ""
set_interface_property KEY4 SVD_ADDRESS_GROUP ""

add_interface_port KEY4 KEY4 key4 Output 1


# 
# connection point AMP1_4
# 
add_interface AMP1_4 conduit end
set_interface_property AMP1_4 associatedClock CLK
set_interface_property AMP1_4 associatedReset RESET
set_interface_property AMP1_4 ENABLED true
set_interface_property AMP1_4 EXPORT_OF ""
set_interface_property AMP1_4 PORT_NAME_MAP ""
set_interface_property AMP1_4 CMSIS_SVD_VARIABLES ""
set_interface_property AMP1_4 SVD_ADDRESS_GROUP ""

add_interface_port AMP1_4 AMP1_4 amp1_4 Output 16


# 
# connection point AMP0_4
# 
add_interface AMP0_4 conduit end
set_interface_property AMP0_4 associatedClock CLK
set_interface_property AMP0_4 associatedReset RESET
set_interface_property AMP0_4 ENABLED true
set_interface_property AMP0_4 EXPORT_OF ""
set_interface_property AMP0_4 PORT_NAME_MAP ""
set_interface_property AMP0_4 CMSIS_SVD_VARIABLES ""
set_interface_property AMP0_4 SVD_ADDRESS_GROUP ""

add_interface_port AMP0_4 AMP0_4 amp0_4 Output 16


# 
# connection point FREQ5
# 
add_interface FREQ5 conduit end
set_interface_property FREQ5 associatedClock CLK
set_interface_property FREQ5 associatedReset RESET
set_interface_property FREQ5 ENABLED true
set_interface_property FREQ5 EXPORT_OF ""
set_interface_property FREQ5 PORT_NAME_MAP ""
set_interface_property FREQ5 CMSIS_SVD_VARIABLES ""
set_interface_property FREQ5 SVD_ADDRESS_GROUP ""

add_interface_port FREQ5 FREQ5 freq5 Output 8


# 
# connection point KEY5
# 
add_interface KEY5 conduit end
set_interface_property KEY5 associatedClock CLK
set_interface_property KEY5 associatedReset RESET
set_interface_property KEY5 ENABLED true
set_interface_property KEY5 EXPORT_OF ""
set_interface_property KEY5 PORT_NAME_MAP ""
set_interface_property KEY5 CMSIS_SVD_VARIABLES ""
set_interface_property KEY5 SVD_ADDRESS_GROUP ""

add_interface_port KEY5 KEY5 key5 Output 1


# 
# connection point AMP1_5
# 
add_interface AMP1_5 conduit end
set_interface_property AMP1_5 associatedClock CLK
set_interface_property AMP1_5 associatedReset RESET
set_interface_property AMP1_5 ENABLED true
set_interface_property AMP1_5 EXPORT_OF ""
set_interface_property AMP1_5 PORT_NAME_MAP ""
set_interface_property AMP1_5 CMSIS_SVD_VARIABLES ""
set_interface_property AMP1_5 SVD_ADDRESS_GROUP ""

add_interface_port AMP1_5 AMP1_5 amp1_5 Output 16


# 
# connection point AMP0_5
# 
add_interface AMP0_5 conduit end
set_interface_property AMP0_5 associatedClock CLK
set_interface_property AMP0_5 associatedReset RESET
set_interface_property AMP0_5 ENABLED true
set_interface_property AMP0_5 EXPORT_OF ""
set_interface_property AMP0_5 PORT_NAME_MAP ""
set_interface_property AMP0_5 CMSIS_SVD_VARIABLES ""
set_interface_property AMP0_5 SVD_ADDRESS_GROUP ""

add_interface_port AMP0_5 AMP0_5 amp0_5 Output 16


# 
# connection point FREQ6
# 
add_interface FREQ6 conduit end
set_interface_property FREQ6 associatedClock CLK
set_interface_property FREQ6 associatedReset RESET
set_interface_property FREQ6 ENABLED true
set_interface_property FREQ6 EXPORT_OF ""
set_interface_property FREQ6 PORT_NAME_MAP ""
set_interface_property FREQ6 CMSIS_SVD_VARIABLES ""
set_interface_property FREQ6 SVD_ADDRESS_GROUP ""

add_interface_port FREQ6 FREQ6 freq6 Output 8


# 
# connection point KEY6
# 
add_interface KEY6 conduit end
set_interface_property KEY6 associatedClock CLK
set_interface_property KEY6 associatedReset RESET
set_interface_property KEY6 ENABLED true
set_interface_property KEY6 EXPORT_OF ""
set_interface_property KEY6 PORT_NAME_MAP ""
set_interface_property KEY6 CMSIS_SVD_VARIABLES ""
set_interface_property KEY6 SVD_ADDRESS_GROUP ""

add_interface_port KEY6 KEY6 key6 Output 1


# 
# connection point AMP1_6
# 
add_interface AMP1_6 conduit end
set_interface_property AMP1_6 associatedClock CLK
set_interface_property AMP1_6 associatedReset RESET
set_interface_property AMP1_6 ENABLED true
set_interface_property AMP1_6 EXPORT_OF ""
set_interface_property AMP1_6 PORT_NAME_MAP ""
set_interface_property AMP1_6 CMSIS_SVD_VARIABLES ""
set_interface_property AMP1_6 SVD_ADDRESS_GROUP ""

add_interface_port AMP1_6 AMP1_6 amp1_6 Output 16


# 
# connection point AMP0_6
# 
add_interface AMP0_6 conduit end
set_interface_property AMP0_6 associatedClock CLK
set_interface_property AMP0_6 associatedReset RESET
set_interface_property AMP0_6 ENABLED true
set_interface_property AMP0_6 EXPORT_OF ""
set_interface_property AMP0_6 PORT_NAME_MAP ""
set_interface_property AMP0_6 CMSIS_SVD_VARIABLES ""
set_interface_property AMP0_6 SVD_ADDRESS_GROUP ""

add_interface_port AMP0_6 AMP0_6 amp0_6 Output 16


# 
# connection point FREQ7
# 
add_interface FREQ7 conduit end
set_interface_property FREQ7 associatedClock CLK
set_interface_property FREQ7 associatedReset RESET
set_interface_property FREQ7 ENABLED true
set_interface_property FREQ7 EXPORT_OF ""
set_interface_property FREQ7 PORT_NAME_MAP ""
set_interface_property FREQ7 CMSIS_SVD_VARIABLES ""
set_interface_property FREQ7 SVD_ADDRESS_GROUP ""

add_interface_port FREQ7 FREQ7 freq7 Output 8


# 
# connection point KEY7
# 
add_interface KEY7 conduit end
set_interface_property KEY7 associatedClock CLK
set_interface_property KEY7 associatedReset RESET
set_interface_property KEY7 ENABLED true
set_interface_property KEY7 EXPORT_OF ""
set_interface_property KEY7 PORT_NAME_MAP ""
set_interface_property KEY7 CMSIS_SVD_VARIABLES ""
set_interface_property KEY7 SVD_ADDRESS_GROUP ""

add_interface_port KEY7 KEY7 key7 Output 1


# 
# connection point AMP1_7
# 
add_interface AMP1_7 conduit end
set_interface_property AMP1_7 associatedClock CLK
set_interface_property AMP1_7 associatedReset RESET
set_interface_property AMP1_7 ENABLED true
set_interface_property AMP1_7 EXPORT_OF ""
set_interface_property AMP1_7 PORT_NAME_MAP ""
set_interface_property AMP1_7 CMSIS_SVD_VARIABLES ""
set_interface_property AMP1_7 SVD_ADDRESS_GROUP ""

add_interface_port AMP1_7 AMP1_7 amp1_7 Output 16


# 
# connection point AMP0_7
# 
add_interface AMP0_7 conduit end
set_interface_property AMP0_7 associatedClock CLK
set_interface_property AMP0_7 associatedReset RESET
set_interface_property AMP0_7 ENABLED true
set_interface_property AMP0_7 EXPORT_OF ""
set_interface_property AMP0_7 PORT_NAME_MAP ""
set_interface_property AMP0_7 CMSIS_SVD_VARIABLES ""
set_interface_property AMP0_7 SVD_ADDRESS_GROUP ""

add_interface_port AMP0_7 AMP0_7 amp0_7 Output 16


# 
# connection point MM_Slave
# 
add_interface MM_Slave avalon end
set_interface_property MM_Slave addressUnits WORDS
set_interface_property MM_Slave associatedClock CLK
set_interface_property MM_Slave associatedReset RESET
set_interface_property MM_Slave bitsPerSymbol 8
set_interface_property MM_Slave burstOnBurstBoundariesOnly false
set_interface_property MM_Slave burstcountUnits WORDS
set_interface_property MM_Slave explicitAddressSpan 0
set_interface_property MM_Slave holdTime 0
set_interface_property MM_Slave linewrapBursts false
set_interface_property MM_Slave maximumPendingReadTransactions 0
set_interface_property MM_Slave maximumPendingWriteTransactions 0
set_interface_property MM_Slave readLatency 0
set_interface_property MM_Slave readWaitStates 0
set_interface_property MM_Slave readWaitTime 0
set_interface_property MM_Slave setupTime 0
set_interface_property MM_Slave timingUnits Cycles
set_interface_property MM_Slave writeWaitTime 0
set_interface_property MM_Slave ENABLED true
set_interface_property MM_Slave EXPORT_OF ""
set_interface_property MM_Slave PORT_NAME_MAP ""
set_interface_property MM_Slave CMSIS_SVD_VARIABLES ""
set_interface_property MM_Slave SVD_ADDRESS_GROUP ""

add_interface_port MM_Slave AVL_ADDR address Input 6
add_interface_port MM_Slave AVL_BYTE_EN byteenable Input 4
add_interface_port MM_Slave AVL_READDATA readdata Output 32
add_interface_port MM_Slave AVL_READ read Input 1
add_interface_port MM_Slave AVL_CS chipselect Input 1
add_interface_port MM_Slave AVL_WRITE write Input 1
add_interface_port MM_Slave AVL_WRITEDATA writedata Input 32
set_interface_assignment MM_Slave embeddedsw.configuration.isFlash 0
set_interface_assignment MM_Slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment MM_Slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment MM_Slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point GLIDE_EN
# 
add_interface GLIDE_EN conduit end
set_interface_property GLIDE_EN associatedClock CLK
set_interface_property GLIDE_EN associatedReset ""
set_interface_property GLIDE_EN ENABLED true
set_interface_property GLIDE_EN EXPORT_OF ""
set_interface_property GLIDE_EN PORT_NAME_MAP ""
set_interface_property GLIDE_EN CMSIS_SVD_VARIABLES ""
set_interface_property GLIDE_EN SVD_ADDRESS_GROUP ""

add_interface_port GLIDE_EN GLIDE_EN glide_en Output 1


# 
# connection point GLIDE_RATE
# 
add_interface GLIDE_RATE conduit end
set_interface_property GLIDE_RATE associatedClock CLK
set_interface_property GLIDE_RATE associatedReset ""
set_interface_property GLIDE_RATE ENABLED true
set_interface_property GLIDE_RATE EXPORT_OF ""
set_interface_property GLIDE_RATE PORT_NAME_MAP ""
set_interface_property GLIDE_RATE CMSIS_SVD_VARIABLES ""
set_interface_property GLIDE_RATE SVD_ADDRESS_GROUP ""

add_interface_port GLIDE_RATE GLIDE_RATE glide_rate Output 24


# 
# connection point ARP_EN
# 
add_interface ARP_EN conduit end
set_interface_property ARP_EN associatedClock CLK
set_interface_property ARP_EN associatedReset ""
set_interface_property ARP_EN ENABLED true
set_interface_property ARP_EN EXPORT_OF ""
set_interface_property ARP_EN PORT_NAME_MAP ""
set_interface_property ARP_EN CMSIS_SVD_VARIABLES ""
set_interface_property ARP_EN SVD_ADDRESS_GROUP ""

add_interface_port ARP_EN ARP_EN arp_en Output 1


# 
# connection point ARP_TIME
# 
add_interface ARP_TIME conduit end
set_interface_property ARP_TIME associatedClock CLK
set_interface_property ARP_TIME associatedReset ""
set_interface_property ARP_TIME ENABLED true
set_interface_property ARP_TIME EXPORT_OF ""
set_interface_property ARP_TIME PORT_NAME_MAP ""
set_interface_property ARP_TIME CMSIS_SVD_VARIABLES ""
set_interface_property ARP_TIME SVD_ADDRESS_GROUP ""

add_interface_port ARP_TIME ARP_TIME arp_time Output 16


# 
# connection point PINGPONGEN
# 
add_interface PINGPONGEN conduit end
set_interface_property PINGPONGEN associatedClock CLK
set_interface_property PINGPONGEN associatedReset RESET
set_interface_property PINGPONGEN ENABLED true
set_interface_property PINGPONGEN EXPORT_OF ""
set_interface_property PINGPONGEN PORT_NAME_MAP ""
set_interface_property PINGPONGEN CMSIS_SVD_VARIABLES ""
set_interface_property PINGPONGEN SVD_ADDRESS_GROUP ""

add_interface_port PINGPONGEN PINGPONGEN pingpongen Output 1


# 
# connection point PANNING
# 
add_interface PANNING conduit end
set_interface_property PANNING associatedClock CLK
set_interface_property PANNING associatedReset ""
set_interface_property PANNING ENABLED true
set_interface_property PANNING EXPORT_OF ""
set_interface_property PANNING PORT_NAME_MAP ""
set_interface_property PANNING CMSIS_SVD_VARIABLES ""
set_interface_property PANNING SVD_ADDRESS_GROUP ""

add_interface_port PANNING PANNING panning Output 16


# 
# connection point AUTO_PAN_EN
# 
add_interface AUTO_PAN_EN conduit end
set_interface_property AUTO_PAN_EN associatedClock CLK
set_interface_property AUTO_PAN_EN associatedReset ""
set_interface_property AUTO_PAN_EN ENABLED true
set_interface_property AUTO_PAN_EN EXPORT_OF ""
set_interface_property AUTO_PAN_EN PORT_NAME_MAP ""
set_interface_property AUTO_PAN_EN CMSIS_SVD_VARIABLES ""
set_interface_property AUTO_PAN_EN SVD_ADDRESS_GROUP ""

add_interface_port AUTO_PAN_EN AUTO_PAN_EN auto_pan_en Output 1


# 
# connection point FILTER_EN
# 
add_interface FILTER_EN conduit end
set_interface_property FILTER_EN associatedClock CLK
set_interface_property FILTER_EN associatedReset ""
set_interface_property FILTER_EN ENABLED true
set_interface_property FILTER_EN EXPORT_OF ""
set_interface_property FILTER_EN PORT_NAME_MAP ""
set_interface_property FILTER_EN CMSIS_SVD_VARIABLES ""
set_interface_property FILTER_EN SVD_ADDRESS_GROUP ""

add_interface_port FILTER_EN FILTER_EN filter_en Output 1


# 
# connection point FILTER_A0
# 
add_interface FILTER_A0 conduit end
set_interface_property FILTER_A0 associatedClock CLK
set_interface_property FILTER_A0 associatedReset ""
set_interface_property FILTER_A0 ENABLED true
set_interface_property FILTER_A0 EXPORT_OF ""
set_interface_property FILTER_A0 PORT_NAME_MAP ""
set_interface_property FILTER_A0 CMSIS_SVD_VARIABLES ""
set_interface_property FILTER_A0 SVD_ADDRESS_GROUP ""

add_interface_port FILTER_A0 FILTER_A0 filter_a0 Output 16


# 
# connection point FILTER_A1
# 
add_interface FILTER_A1 conduit end
set_interface_property FILTER_A1 associatedClock CLK
set_interface_property FILTER_A1 associatedReset ""
set_interface_property FILTER_A1 ENABLED true
set_interface_property FILTER_A1 EXPORT_OF ""
set_interface_property FILTER_A1 PORT_NAME_MAP ""
set_interface_property FILTER_A1 CMSIS_SVD_VARIABLES ""
set_interface_property FILTER_A1 SVD_ADDRESS_GROUP ""

add_interface_port FILTER_A1 FILTER_A1 filter_a1 Output 16


# 
# connection point FILTER_A2
# 
add_interface FILTER_A2 conduit end
set_interface_property FILTER_A2 associatedClock CLK
set_interface_property FILTER_A2 associatedReset ""
set_interface_property FILTER_A2 ENABLED true
set_interface_property FILTER_A2 EXPORT_OF ""
set_interface_property FILTER_A2 PORT_NAME_MAP ""
set_interface_property FILTER_A2 CMSIS_SVD_VARIABLES ""
set_interface_property FILTER_A2 SVD_ADDRESS_GROUP ""

add_interface_port FILTER_A2 FILTER_A2 filter_a2 Output 16


# 
# connection point FILTER_B0
# 
add_interface FILTER_B0 conduit end
set_interface_property FILTER_B0 associatedClock CLK
set_interface_property FILTER_B0 associatedReset ""
set_interface_property FILTER_B0 ENABLED true
set_interface_property FILTER_B0 EXPORT_OF ""
set_interface_property FILTER_B0 PORT_NAME_MAP ""
set_interface_property FILTER_B0 CMSIS_SVD_VARIABLES ""
set_interface_property FILTER_B0 SVD_ADDRESS_GROUP ""

add_interface_port FILTER_B0 FILTER_B0 filter_b0 Output 16


# 
# connection point FILTER_B1
# 
add_interface FILTER_B1 conduit end
set_interface_property FILTER_B1 associatedClock CLK
set_interface_property FILTER_B1 associatedReset ""
set_interface_property FILTER_B1 ENABLED true
set_interface_property FILTER_B1 EXPORT_OF ""
set_interface_property FILTER_B1 PORT_NAME_MAP ""
set_interface_property FILTER_B1 CMSIS_SVD_VARIABLES ""
set_interface_property FILTER_B1 SVD_ADDRESS_GROUP ""

add_interface_port FILTER_B1 FILTER_B1 filter_b1 Output 16


# 
# connection point FILTER_B2
# 
add_interface FILTER_B2 conduit end
set_interface_property FILTER_B2 associatedClock CLK
set_interface_property FILTER_B2 associatedReset ""
set_interface_property FILTER_B2 ENABLED true
set_interface_property FILTER_B2 EXPORT_OF ""
set_interface_property FILTER_B2 PORT_NAME_MAP ""
set_interface_property FILTER_B2 CMSIS_SVD_VARIABLES ""
set_interface_property FILTER_B2 SVD_ADDRESS_GROUP ""

add_interface_port FILTER_B2 FILTER_B2 filter_b2 Output 16


# 
# connection point DELAY_EN
# 
add_interface DELAY_EN conduit end
set_interface_property DELAY_EN associatedClock CLK
set_interface_property DELAY_EN associatedReset ""
set_interface_property DELAY_EN ENABLED true
set_interface_property DELAY_EN EXPORT_OF ""
set_interface_property DELAY_EN PORT_NAME_MAP ""
set_interface_property DELAY_EN CMSIS_SVD_VARIABLES ""
set_interface_property DELAY_EN SVD_ADDRESS_GROUP ""

add_interface_port DELAY_EN DELAY_EN delay_en Output 1


# 
# connection point DELAY_FEEDBACK
# 
add_interface DELAY_FEEDBACK conduit end
set_interface_property DELAY_FEEDBACK associatedClock CLK
set_interface_property DELAY_FEEDBACK associatedReset ""
set_interface_property DELAY_FEEDBACK ENABLED true
set_interface_property DELAY_FEEDBACK EXPORT_OF ""
set_interface_property DELAY_FEEDBACK PORT_NAME_MAP ""
set_interface_property DELAY_FEEDBACK CMSIS_SVD_VARIABLES ""
set_interface_property DELAY_FEEDBACK SVD_ADDRESS_GROUP ""

add_interface_port DELAY_FEEDBACK DELAY_FEEDBACK delay_feedback Output 16


# 
# connection point DELAY_TIME
# 
add_interface DELAY_TIME conduit end
set_interface_property DELAY_TIME associatedClock CLK
set_interface_property DELAY_TIME associatedReset ""
set_interface_property DELAY_TIME ENABLED true
set_interface_property DELAY_TIME EXPORT_OF ""
set_interface_property DELAY_TIME PORT_NAME_MAP ""
set_interface_property DELAY_TIME CMSIS_SVD_VARIABLES ""
set_interface_property DELAY_TIME SVD_ADDRESS_GROUP ""

add_interface_port DELAY_TIME DELAY_TIME delay_time Output 32

